#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

url: 'http://nghin.github.io/vacsf.org.dev'
baseurl: ''
projectname: ''
# urlimg: 'http://0.0.0.0:4000/images/'
urlimg: 'http://nghin.github.io/vacsf.org.dev/images/'

sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded
  line_numbers: true
  # trace_selectors: true
  # debug_info: true
  # FUTURE https://github.com/jekyll/jekyll-sass-converter/issues/12
  sourcemap: true

# Disable when not in production
google_analytics_tracking_id: UA-62532661-1
google_site_verification: raAW1dX3u8aKibVvvHhyP_wSzIW5LATk9MPMzLo3yyo
